# Nombre de la aplicación
spring.application.name=Bitacora-digital

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/teia_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=teia_user
spring.datasource.password=teia_password

# Configuración de Hibernate/JPA
# En desarrollo puedes usar "update" para que te cree/ajuste tablas
# En producción conviene usar "validate" o "none"
spring.jpa.hibernate.ddl-auto=update

# Mostrar las queries SQL en consola (útil en desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto optimizado para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
